stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: noninteractive
  SCALENODE_CPU: 2
  SCALENODE_RAM: 4096
  SCALENODE_DISK: 8
  PYENV_ROOT: .pyenv

install_pyenv:
  image: debian:bookworm
  stage: build
  before_get_sources:
    - apt -qqy update 2> /dev/null > /dev/null
    - apt -qqy install --no-install-recommends build-essential curl git wget xz-utils tk-dev libssl-dev libxml2-dev libxmlsec1-dev libreadline-dev zlib1g-dev libffi-dev libbz2-dev libncurses-dev libsqlite3-dev liblzma-dev python3 python3-pip python3-dev python3-venv 2> /dev/null > /dev/null
  script:
    - curl https://pyenv.run | bash
  artifacts:
    paths:
      - $PYENV_ROOT

test:
  image: debian:bookworm
  stage: test
  dependencies: ["install_pyenv"]
  parallel: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
  before_get_sources:
    - apt -qqy update 2> /dev/null > /dev/null
    - apt -qqy install --no-install-recommends build-essential curl git wget xz-utils tk-dev libssl-dev libxml2-dev libxmlsec1-dev libreadline-dev zlib1g-dev libffi-dev libbz2-dev libncurses-dev libsqlite3-dev liblzma-dev python3 python3-pip python3-dev python3-venv 2> /dev/null > /dev/null
  script:
    - export PATH="$PYENV_ROOT/bin:$PATH"
    - export PATH="$PYENV_ROOT/shims:$PATH"
    - pyenv install $CI_PARALLEL_NAME
    - pyenv global $CI_PARALLEL_NAME
    - python3 -V
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install .
    - python3 tests/test_exporter.py
